[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
heapless = { version = "0.9.2" }

bytes = { version = "1.11.1" }
darling = { version = "0.23.0" }
proc-macro2 = { version = "1.0.106" }
quote = { version = "1.0.45" }
syn = { version = "2.0.117" }
trybuild = { version = "1.0.116" }
proptest = { version = "1.10.0" }
serde = { version = "1.0.228" }
tokio-util = { version = "0.7.18" }
derive_more = { version = "2.1.1" }

acex-d = { path = "crates/acex-d", version = "0.5.3" }
acex-core = { path = "crates/acex-core", version = "0.5.3" }
acex-macros = { path = "crates/acex-macros", version = "0.5.3" }
acex-proto = { path = "crates/acex-proto", version = "0.5.3" }
acex-can = { path = "crates/acex-can", version = "0.5.3" }
acex-sim = { path = "crates/acex-sim", version = "0.5.3" }
acex-uds = { path = "crates/acex-uds", version = "0.5.3" }
acex-doip = { path = "crates/acex-doip", version = "0.5.3" }
acex-server = { path = "crates/acex-server", version = "0.5.3" }
acex-client = { path = "crates/acex-client", version = "0.5.3" }
acex-gateway = { path = "crates/acex-gateway", version = "0.5.3" }
acex-transport = { path = "crates/acex-transport", version = "0.5.3" }
