[package]
name = "acex-doip"
version = "0.5.3"
edition = "2024"
authors = ["Samuel Preston <samp.reston@outlook.com>", "MRW <171420035+MRWGNRRR@users.noreply.github.com>"]
description = "DoIP typed message and session layer implementing ISO 13400-2."
readme = "README.md"
repository = "https://github.com/MRWGNRRR/acex"
license = "MIT or Apache-2.0"
keywords = ["diagnostics", "vehicle", "standards"]
categories = ["development-tools", "network-programming", "automotive"]

[features]
default = []
serde = ["dep:serde"]
alloc = [
	"acex-core/alloc",
	"acex-proto/alloc",
	"acex-uds/alloc",
	"acex-macros/alloc",
	"acex-sim/alloc",
]
std = ["alloc", "acex-core/std", "acex-proto/std", "acex-sim/std"]
tokio = ["dep:tokio-util", "alloc", "dep:bytes"]

[dependencies]
acex-macros = { workspace = true }
acex-core = { workspace = true }
acex-proto = { workspace = true }
acex-uds = { workspace = true }
acex-sim = { workspace = true }

derive_more = { workspace = true, features = ["display", "from"] }
bytes = { workspace = true, optional = true }
heapless = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }
tokio-util = { workspace = true, optional = true, features = ["codec"] }

[dev-dependencies]
proptest = { workspace = true }
acex-core = { workspace = true }
bytes = { workspace = true }
