[package]
name = "acex-client"
version = "0.5.3"
edition = "2024"
authors = ["Samuel Preston <samp.reston@outlook.com>", "MRW <171420035+MRWGNRRR@users.noreply.github.com>"]
description = "UDS tester client state machine."
readme = "README.md"
repository = "https://github.com/MRWGNRRR/acex"
license = "MIT or Apache-2.0"
keywords = ["diagnostics", "vehicle", "standards"]
categories = ["development-tools", "network-programming", "automotive"]

[features]
default = []
alloc = ["acex-core/alloc", "acex-uds/alloc", "acex-proto/alloc", "acex-sim/alloc"]
std = [
	"alloc",
	"acex-core/std",
	"acex-uds/std",
	"acex-sim/std",
	"acex-proto/std",
	"acex-sim/std",
]

[dependencies]
acex-core = { workspace = true }
acex-proto = { workspace = true }
acex-uds = { workspace = true }
acex-sim = { workspace = true }

[dev-dependencies]
acex-server = { workspace = true }
